version: '3.8'

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE} #postgres
      POSTGRES_USER: ${POSTGRES_USER} #postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} #pass12345
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  local_pgdata: